# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go build for Linux amd64

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-20.04 # compatible with Debian bullseye
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Install libpcap dependency
      run: |
        sudo apt update
        sudo apt install -y golang-github-google-gopacket-dev

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

    - name: Upload generated binary
      uses: actions/upload-artifact@v3
      with:
        name: virtwold-linux-amd64
        path: virtwold
